version: '3.9'

services:
  blogs-database:
    image: postgres:latest
    container_name: blogs-database
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mezonblogs
    ports:
      - '5439:5432'
    volumes:
      - ./db_data/mezonblogs:/var/lib/postgresql/data
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data:rw
    ports:
      - '9000:9000'
      - '9001:9001'

  mc-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5 &&
        mc alias set local http://minio:9000 minioadmin minioadmin &&
        mc mb local/mezonblogs || true &&
        mc anonymous set download local/mezonblogs || true &&
        echo '✅ MinIO bucket mezonblogs ready with public read access'
      "
